kind: pipeline
type: kubernetes
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: iotcat/ushio-session
    username: 
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
